name: YouTube Live Stream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install ffmpeg -y

    - name: Start YouTube Live Stream
      run: |
        ffmpeg -re -i "https://path-to-your-video.mp4" -c:v libx264 -preset fast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/YOUR_STREAM_KEY"
